### ISSUE TITLE
Correct Items not displaying.

### ISSUE THREAD

**Issue by AzureDoom** [AustereTony-MCMods/Oxygen-Daily-Rewards#1]
Used the itemstack command to generate a json of the item I was holding, then I copied over the needed info to the rewards for this month, however I keep getting random items that aren't the items I choose. The count is the correct amount but the item is wrong. Given item is the wrong item as well.

**Comment by AustereTony-MCMods** [comment]
Should be fixed in 0.10.1.

**Comment by AustereTony-MCMods** [comment]
Consider it closed.
